name: whisper-ui
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.01.10=h06a4308_0
  - certifi=2022.9.24=py311h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=1.1.1s=h7f8727e_0
  - pip=22.2.2=py311h06a4308_0
  - python=3.11.0=h7a1cb2a_2
  - readline=8.2=h5eee18b_0
  - setuptools=65.5.0=py311h06a4308_0
  - sqlite=3.40.1=h5082296_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.10=h5eee18b_1
  - zlib=1.2.13=h5eee18b_0
  - pip:
    - altair==4.2.2
    - attrs==22.2.0
    - blinker==1.5
    - cachetools==5.3.0
    - charset-normalizer==3.0.1
    - click==8.1.3
    - decorator==5.1.1
    - entrypoints==0.4
    - ffmpeg-python==0.2.0
    - filelock==3.9.0
    - future==0.18.3
    - gitdb==4.0.10
    - gitpython==3.1.30
    - greenlet==2.0.2
    - huggingface-hub==0.12.0
    - idna==3.4
    - importlib-metadata==6.0.0
    - jinja2==3.1.2
    - jsonschema==4.17.3
    - markdown-it-py==2.1.0
    - markupsafe==2.1.2
    - mdurl==0.1.2
    - more-itertools==9.0.0
    - numpy==1.24.2
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - openai-whisper==20230124
    - packaging==23.0
    - pandas==1.5.3
    - pillow==9.4.0
    - protobuf==3.20.3
    - pyarrow==11.0.0
    - pydeck==0.8.0
    - pygments==2.14.0
    - pympler==1.0.1
    - pyrsistent==0.19.3
    - python-dateutil==2.8.2
    - pytube==12.1.2
    - pytz==2022.7.1
    - pytz-deprecation-shim==0.1.0.post0
    - pyyaml==6.0
    - regex==2022.10.31
    - requests==2.28.2
    - rich==13.3.1
    - semver==2.13.0
    - six==1.16.0
    - smmap==5.0.0
    - sqlalchemy==2.0.2
    - streamlit==1.17.0
    - tokenizers==0.13.2
    - toml==0.10.2
    - toolz==0.12.0
    - torch==1.13.1
    - tornado==6.2
    - tqdm==4.64.1
    - transformers==4.26.0
    - typing-extensions==4.4.0
    - tzdata==2022.7
    - tzlocal==4.2
    - urllib3==1.26.14
    - validators==0.20.0
    - watchdog==2.2.1
    - zipp==3.12.1
